version: 2
updates:
- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  reviewers:
  - garethjevans
- package-ecosystem: gomod
  directory: "/"
  groups:
    kubernetes:
      patterns:
      - "k8s.io/*"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  reviewers:
  - garethjevans
