before:
  hooks:
  - go mod download

builds:
- id: kubectl-permissions
  main: ./cmd/kubectl-permissions.go
  binary: kubectl-permissions
  ldflags:
    - -X github.com/garethjevans/kubectl-permissions/pkg/version.Version={{.Version}}
  env:
  - CGO_ENABLED=0
  goos:
  - linux
  - darwin
  - windows
  goarch:
  - amd64
  - arm64
  ignore:
  - goos: windows
    goarch: arm64

source:
  enabled: true

sboms:
- artifacts: archive
- id: source
  artifacts: source

checksum:
  name_template: 'checksums.txt'

signs:
- id: kubectl-permissions
  cmd: cosign
  env:
    - COSIGN_EXPERIMENTAL=1
  certificate: '${artifact}.pem'
  args:
    - sign-blob
    - '--output-certificate=${certificate}'
    - '--output-signature=${signature}'
    - '${artifact}'
  artifacts: checksum
  output: true

archives:
- builds:
  - kubectl-permissions
  name_template: "{{ .ProjectName }}_{{ .Tag }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"
  wrap_in_directory: false
  format: tar.gz
  files:
  - LICENSE
